development:
  sessions:
    default:
      database: carmatec
      hosts:
        - localhost:27017
      options:
  options:
   
test:
  sessions:
    default:
      database: carmatec
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: carmatec
      hosts:
        - localhost:27017
      options:        
